<?
  include_once ("../../../../lib/inc.php");

  // identity check

  if (!postcheck ($_REQUEST, ["cid", "multiedit"]))
  {
    $apireturn["status"]["success"] = "false";
    $apireturn["status"]["error"] = "Missing fields";
  }
  else
  {
      // everything ok

      $multi = explode ("\n", $_REQUEST["multiedit"]);

      if (sizeof ($multi))
      {
        mysqli_begin_transaction ($mysql, MYSQLI_TRANS_START_READ_WRITE);

        foreach ($multi as $m)
        {
          preg_match_all ('/^(\*)?(\+)?([0-9]*)>>(.*)<<(.*)/i', $m, $matches);
          $apireturn["works"][] = ["id" => $matches[3][0], "title" => $matches[4][0], "subtitle" => $matches[5][0], "recommended" => ($matches[1][0] == "*" ? 1 : 0), "popular" => ($matches[2][0] == "+" ? 1 : 0)];
          
          mysqli_query ($mysql, "update work set title='". mysqli_real_escape_string ($mysql, $matches[4][0]). "', subtitle='". mysqli_real_escape_string ($mysql, $matches[5][0]). "', recommended=". ($matches[1][0] == "*" ? 1 : 0). ", popular=". ($matches[2][0] == "+" ? 1 : 0). " where id = '{$matches[3][0]}'");
        }

        mysqli_commit ($mysql);

        $apireturn["status"]["success"] = "true";
        $apireturn["status"]["updated_rows"] = sizeof ($multi);

        shell_exec ("rm ". WEBDIR. "/genre/list/composer/{$_REQUEST["cid"]}.json");
        shell_exec ("rm ". WEBDIR. "/work/list/composer/{$_REQUEST["cid"]}/ -rf");
      }
      else
      {
        $apireturn["status"]["success"] = "false";
      }

      $apireturn["composer"]["id"] = $_REQUEST["cid"];
  }

  echo apireturn ($apireturn);
