<?
  include_once ("../../../../lib/inc.php");

  // identity check

  if (!simpleauth ($mysql, $_REQUEST["id"], $_REQUEST["auth"]))
  {
    $apireturn["status"]["success"] = "false";
    $apireturn["status"]["error"] = "Authentication failed";
  }
  else if (!postcheck ($_REQUEST, ["wid", "composer_id", "title", "genre", "uni_id"]))
  {
    $apireturn["status"]["success"] = "false";
    $apireturn["status"]["error"] = "Missing fields";
  }
  else
  {
      // everything ok

      $update = Array (
        "composer_id" => $_REQUEST["composer_id"], 
        "title" => $_REQUEST["title"],
        "genre" => $_REQUEST["genre"],
        "year" => $_REQUEST["year"],
        "recommended" => $_REQUEST["recommended"],
        "uni_id" => $_REQUEST["uni_id"]
      );

      $where = Array (
        "id" => $_REQUEST["wid"]
      );

      $op = mysqlupdate ($mysql, "work", $update, $where);

      if ($op >= 1)
      {
        $apireturn["status"]["success"] = "true";

        shell_exec ("rm ". WEBDIR. "/genre/list/composer/{$_REQUEST["composer_id"]}.json");
        shell_exec ("rm ". WEBDIR. "/work/list/composer/{$_REQUEST["composer_id"]}/ -rf");
        shell_exec ("rm ". WEBDIR. "/recording/list/work/{$_REQUEST["wid"]}.json");
      }
      else
      {
        $apireturn["status"]["success"] = "false";
      }

      $apireturn["status"]["updated_rows"] = $op;
      $apireturn["user"]["id"] = $_REQUEST["id"];
      $apireturn["work"] = $update;
      $apireturn["work"]["id"] = $_REQUEST["wid"];
  }

  echo apireturn ($apireturn);
