<?
  include_once ("../../../../lib/inc.php");

  // identity check

  if (!simpleauth ($mysql, $_REQUEST["id"], $_REQUEST["auth"]))
  {
    $apireturn["status"]["success"] = "false";
    $apireturn["status"]["error"] = "Authentication failed";
  }
  else if (!postcheck ($_REQUEST, ["wid"]))
  {
    $apireturn["status"]["success"] = "false";
    $apireturn["status"]["error"] = "Missing fields";
  }
  else
  {
      $query = "select title, composer.id as cid, composer.name as name, composer.complete_name as complete_name from work, composer where work.id='{$_REQUEST["wid"]}' and composer.id=work.composer_id";
      $work = mysqlfetch ($mysql, $query);

      $apireturn["work"]["id"] = $_REQUEST["wid"];

      if ($work)
      {
        $apireturn["status"]["success"] = "true";
        $apireturn["work"]["title"] = $work[0]["title"];
        $apireturn["composer"] = Array ("id" => $work[0]["cid"], "name" => $work[0]["name"], "complete_name" => $work[0]["complete_name"]);

        $token = spotifyauth ();
        $spotifyalbum = spotifydownparse (SPOTIFYAPI. "/search/?type=album&q=". urlencode (worksimplifier ($work[0]["title"]). " artist:{$work[0]["complete_name"]}"), $token);
        
        print_r ($spotifyalbum);
      }
      else
      {
        $apireturn["status"]["success"] = "false";
        $apireturn["status"]["error"] = "Work not found";
      }
  }

  echo apireturn ($apireturn);
